name: Train and Evaluate Models

on:
  push:
    branches: [ "main" ]

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python test_train_model.py

      - name: Evaluate models
        run: python evaluate_model.py
